# Generated by Django 2.1.7 on 2019-04-03 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='remaining_invitations',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='used_invitations',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
